Imports System
Imports System.Text

Module Program
    Sub Main(args As String())
        ' Credits:
        ' #1 Art by Hayley Jane Wakenshaw
        ' #2 Art by Dirk-Lueder Kreie
        ' #3 Art by Donovan Bake
        ' #7  Art by Donovan Bake
        ' Source: https://www.asciiart.eu/animals/insects/snails

        Dim b64 As String() = {
            "ICAgIC4tLS0tLiAgIEAgICBACiAgIC8gLi0iLS5gLiAgXHYvCiAgIHwgfCAnXCBcIFxfLyApCiAsLVwgYC0uJyAvLicgIC8KJy0tLWAtLS0tJy0tLS0n",
            "ICAgICAgICAgX18sLl8KICAgICAgICAvICBfICBcICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICB8ICA2IFwgIFwgIG9vICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgIFxfX18vIC58X198fCAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiBfXywuLj0iXiAgLiAsICIgICwgXCAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAo8Ll9fX19fX19fX19fX19fX19fXy8=",
            "ICAgIF9fX19fXyAgICAgICAgICAKICAgLyAgX19fIFwgICAgICAgICAKICB8ICAvICwuXCB8TyAgICBPICAKICB8IHwgIFxkLyB8IFxfXy8gICAKICB8X19cX19fX18vLSguLikgICAKXy9fX19fX19fX19fX19fLyBkd2I=",
            "byAgICAgICBvCiBcX19fX18vIAogLz1PPU89XCAgICAgX19fX19fXyAKLyAgIF4gICBcICAgL1xcXFxcXFxcClwgXF9fXy8gLyAgL1wgICBfX18gIFwKIFxfIFYgXy8gIC9cICAgL1xcXFwgIFwKICAgXCAgXF9fL1wgICAvXCBAXy8gIC8KICAgIFxfX19fXF9fX19cX19fX19fLw==",
            "QCAgICAgICAgICAgICBfX19fX19fX18KIFxfX19fICAgICAgIC8gICAgICAgICBcCiAvICAgIFwgICAgIC8gICBfX19fICAgIFwKIFxfICAgIFwgICAvICAgLyAgICBcICAgIFwKICAgXCAgICBcICggICAgXF9fLyAgKSAgICApCiAgICBcICAgIFxfXCBcX19fX19fLyAgICAvCiAgICAgXCAgICAgIFwgICAgICAgICAgIC9fX18KICAgICAgXF9fX19fX1xfX19fX19fX18vX19fXyItXw==",
            "ICAgICAvXlwgICAgL15cCiAgICB7ICBPfSAgeyAgT30KICAgICBcIC8gICAgXCAvCiAgICAgLy8gICAgIC8vICAgICAgIF8tLS0tLS1fCiAgICAvLyAgICAgLy8gICAgIC4vfiAgICAgICAgfi1fCiAgIC8gfi0tLS1+LyAgICAgLyAgICAgICAgICAgICAgXAogLyAgICAgICAgIDogICAuLyAgICAgICBfLS0tXyAgICB+LQp8ICBcX19fX19fX18pIDogICAgICAgL34gICAgIH5cICAgfAp8ICAgICAgICAvICAgIHwgICAgICB8ICA6fn5cICB8ICAgfAp8ICAgICAgIHwgICAgIHwgICAgICB8ICBcX19fLX4gICAgfAp8ICAgICAgICBcIF9fL2BeXF9fX19fX1wuICAgICAgICAuLwogXCAgICAgICAgICAgICAgICAgICAgIH4tX19fX19fLX5cLgogLnwgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIH4tXwovX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX35+X19fXw==",
            "ICAgICAgICAgICBlZWQqIiIiIiIiIiIiKipiZSwKICAgICAgICAuZCIgICAgICAgICAgICAgICAgICAiYi4KICAgICAgLmQgICAgICAgICAgICAgICAgICAgICAgICBiLgogICAgLiIgICAgICAgICAuLmVlZWVlZS4uICAgICAgICAgIi4KICAgUCAgICAgICAgeiQqIiAgICAgICAgIiplLiAgICAgICAgOS4KICBBICAgICAgIGQiICAgICAgICAgICAgICAgICJiICAgICAgIEEKIEogICAgICAgSiAgICAuZSoiIiIiIiIlYyAgICAgQSAgICAgICBMCkEgICAgICAgQSAgICBkIiAgICAgICAgICAkICAgICBMICAgICAgQQojICAgICAgICUgICBkICAgICAgZCoqeSAgJ0wgICAgJSAgICAgICMKIyAgICAgICAlICAgJCAgICAgJCAsLCBZICAuJCAgICUgICAgICAjICAgICAgIF8gXyAKIyAgICAgICAlICAgJCAgICAgKiAgIiIiICAgRiAgICUgICAgICAjICAgICAgKEApQCkKIyAgICAgICBWICAgIDQuICAgICQuICAgLmUiICAgIFkgICAgICAjICAgICAgICAlICUKIyAgICAgICAgJCAgICAqLiAgICAiIiIiICAgICAuWSAgICAgIFYgICAgICAgICAkICQKIyAgICAgICAgJ2IgICAgICJiLiAgICAgIC4uZSogICAgICAgWSAgICAgICAgIC5lZWVlClYgICAgICAgICAnJCAgICAgICIiZWVlZSIiICAgICAgICBlUCAgICAgICAgIEEgICAgICUKIFkgICAgICAgICBlYiAgICAgICAgICAgICAgICAuLmQqIiAgICAgICAgIF8jICAgIE8gJQogSSAgICBfZSUqIiIiIiokZWUuLi4uLi5lZSQqImVlZWVlZWVlemVlJCoqIiAgICAgICAkCiAgViAsIiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgQgogIEonICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIF8sZT0iIgouJyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjI0RXQicn"
            }

        Dim random As New Random()
        Dim randomIndex As Integer = random.Next(0, b64.Length)
        If b64.Length > 0 Then
            Dim base64String As String = b64(randomIndex)
            Dim decodedString As String = DecodeBase64String(base64String)
            Console.WriteLine(decodedString)
        Else
            Console.WriteLine("No snails found.")
        End If
        If args.Length > 0 Then
            Dim firstArgument As String = args(0)
            Console.WriteLine(firstArgument & "!")
        End If
    End Sub

    Function DecodeBase64String(base64String As String) As String
        Dim base64EncodedBytes As Byte() = Convert.FromBase64String(base64String)
        Dim decodedString As String = Encoding.UTF8.GetString(base64EncodedBytes)
        Return decodedString
    End Function
End Module
